service: podcast-translator

frameworkVersion: '2'

# custom:
#   sourceAudioBucketName: podcast-source-audio-bucket
#   sourceTranscriptionBucketName: podcast-source-transcription-bucket

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  startTranscribe:
    handler: bin/startTranscribe
    events:
      - s3:
          bucket: podcast-source-audio-bucket
          existing: true
          event: s3:ObjectCreated:*

  processTranscribe:
    handler: bin/processTranscribe
    events:
      - s3:
          bucket: podcast-source-transcription-bucket
          existing: true
          event: s3:ObjectCreated:*


    
